# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca06d0e4fafa9301e41d6cfb47a480d2fb27a3be75a3df68a5077e447e250e27ac1535525cb3ed96a79e10ad41fb45bf223df7dfd82eb941418685c601563780

test:
  secret_key_base: e39e2ea8e9f7351bfe83a06dcbece6594297a627ed73d96b37520ee7fe179bb7a90808db55f41618692ef42770819665a1247bc5a8b288fc067ed309fe80a108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
